-- ==============================================================================
-- LAGNA SETU — ALL 143 GUJARATI CASTES MASTER SEED
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.castes (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    guj VARCHAR(150),
    caste_group VARCHAR(100),
    keywords TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS & Public Read
ALTER TABLE public.castes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Castes are viewable by everyone" ON public.castes;
CREATE POLICY "Castes are viewable by everyone" ON public.castes FOR SELECT USING (true);

INSERT INTO public.castes (name, guj, caste_group, keywords) VALUES
    ('Kadva Patidar', 'કડવા પાટીદાર', 'Patidar / Patel', 'kadva patel kadwa patidar kadvapatel કડવા પટેલ પાટીદાર'),
    ('Leva Patidar', 'લેવા પાટીદાર', 'Patidar / Patel', 'leva patel leuva patidar leuvad lewapatel લેવા પટેલ લેઉવા પાટીદાર'),
    ('Anjana (Chaudhary) Patidar', 'આંજણા ચૌધરી પાટીદાર', 'Patidar / Patel', 'anjana chaudhary chaudhari patel anjana patel આંજણા ચૌધરી પટેલ'),
    ('Matiya Patidar', 'મતિયા પાટીદાર', 'Patidar / Patel', 'matiya patel matia patidar મતિયા પટેલ'),
    ('Audichya Sahastra Brahmin', 'ઔદીચ્ય સહસ્ર બ્રાહ્મણ', 'Brahmin', 'audichya sahastra sahasra brahmin ઔદીચ્ય સહસ્ર બ્રાહ્મણ'),
    ('Audichya Zalawadi Brahmin', 'ઔદીચ્ય ઝાલાવાડી બ્રાહ્મણ', 'Brahmin', 'audichya zalawadi jhalawadi brahmin ઔદીચ્ય ઝાલાવાડી બ્રાહ્મણ'),
    ('Audichya Tolkiya Brahmin', 'ઔદીચ્ય ટોળકીયા બ્રાહ્મણ', 'Brahmin', 'audichya tolkiya tolkia brahmin ઔદીચ્ય ટોળકીયા બ્રાહ્મણ'),
    ('Nagar Brahmin', 'નાગર બ્રાહ્મણ', 'Brahmin', 'nagar brahmin vadnagara visnagara prashnora નાગર બ્રાહ્મણ'),
    ('Vadnagara Nagar Brahmin', 'વડનગરા નાગર બ્રાહ્મણ', 'Brahmin', 'vadnagara vadnagari nagar brahmin વડનગરા નાગર બ્રાહ્મણ'),
    ('Visnagara Nagar Brahmin', 'વિસનગરા નાગર બ્રાહ્મણ', 'Brahmin', 'visnagara visnagari nagar brahmin વિસનગરા નાગર બ્રાહ્મણ'),
    ('Prashnora Nagar Brahmin', 'પ્રશ્નોરા નાગર બ્રાહ્મણ', 'Brahmin', 'prashnora nagar brahmin પ્રશ્નોરા નાગર બ્રાહ્મણ'),
    ('Modh Brahmin', 'મોઢ બ્રાહ્મણ', 'Brahmin', 'modh brahmin modhbrahmin મોઢ બ્રાહ્મણ'),
    ('Shrimali Brahmin', 'શ્રીમાળી બ્રાહ્મણ', 'Brahmin', 'shrimali srimali brahmin શ્રીમાળી બ્રાહ્મણ'),
    ('Khedaval Brahmin', 'ખેડાવાલ બ્રાહ્મણ', 'Brahmin', 'khedaval khedawal brahmin ખેડાવાલ બ્રાહ્મણ'),
    ('Rajgor Brahmin', 'રાજગોર બ્રાહ્મણ', 'Brahmin', 'rajgor rajgar brahmin રાજગોર બ્રાહ્મણ'),
    ('Bardai Brahmin', 'બારડાઈ બ્રાહ્મણ', 'Brahmin', 'bardai brahmin બારડાઈ બ્રાહ્મણ'),
    ('Sompura Brahmin', 'સોમપુરા બ્રાહ્મણ', 'Brahmin', 'sompura brahmin sompura salat સોમપુરા બ્રાહ્મણ'),
    ('Trivedi Mewada Brahmin', 'ત્રિવેદી મેવાડા બ્રાહ્મણ', 'Brahmin', 'trivedi mewada mevada brahmin ત્રિવેદી મેવાડા બ્રાહ્મણ'),
    ('Bhatt Mewada Brahmin', 'ભટ્ટ મેવાડા બ્રાહ્મણ', 'Brahmin', 'bhatt mewada mevada brahmin ભટ્ટ મેવાડા બ્રાહ્મણ'),
    ('Tapodhan Brahmin', 'તપોધન બ્રાહ્મણ', 'Brahmin', 'tapodhan tapodhan brahmin તપોધન બ્રાહ્મણ'),
    ('Saraswat Brahmin', 'સારસ્વત બ્રાહ્મણ', 'Brahmin', 'saraswat saraswata brahmin સારસ્વત બ્રાહ્મણ'),
    ('Pushkarna Brahmin', 'પુષ્કર્ણા બ્રાહ્મણ', 'Brahmin', 'pushkarna pokharna brahmin પુષ્કર્ણા બ્રાહ્મણ'),
    ('Gurjar Brahmin', 'ગુર્જર બ્રાહ્મણ', 'Brahmin', 'gurjar gujjar brahmin ગુર્જર બ્રાહ્મણ'),
    ('Sorthiya Brahmin', 'સોરઠીયા બ્રાહ્મણ', 'Brahmin', 'sorthiya sorathiya brahmin સોરઠીયા બ્રાહ્મણ'),
    ('Kandolia Brahmin', 'કંદોળીયા બ્રાહ્મણ', 'Brahmin', 'kandolia kandoliya brahmin કંદોળીયા બ્રાહ્મણ'),
    ('Jambu Brahmin', 'જંબુ બ્રાહ્મણ', 'Brahmin', 'jambu brahmin જંબુ બ્રાહ્મણ'),
    ('Sachora Brahmin', 'સાચોરા બ્રાહ્મણ', 'Brahmin', 'sachora sanchora brahmin સાચોરા બ્રાહ્મણ'),
    ('Gomtiwal Brahmin', 'ગોમતીવાલ બ્રાહ્મણ', 'Brahmin', 'gomtiwal gomtival brahmin ગોમતીવાલ બ્રાહ્મણ'),
    ('Karadia Rajput', 'કારડીયા રાજપૂત', 'Kshatriya / Rajput', 'karadia karadiya rajput kshatriya કારડીયા રાજપૂત ક્ષત્રિય'),
    ('Nadoda Rajput', 'નાદોડા રાજપૂત', 'Kshatriya / Rajput', 'nadoda nadoda rajput નાદોડા રાજપૂત'),
    ('Garasiya Rajput', 'ગરાસિયા રાજપૂત', 'Kshatriya / Rajput', 'garasiya girasiya rajput kshatriya ગરાસિયા રાજપૂત'),
    ('Gurjar Kshatriya', 'ગુર્જર ક્ષત્રિય', 'Kshatriya / Rajput', 'gurjar gujjar kshatriya ગુર્જર ક્ષત્રિય'),
    ('Kshatriya Rajput', 'ક્ષત્રિય રાજપૂત', 'Kshatriya / Rajput', 'rajput rathod vaghela chauhan parmar gohil jadeja jhala solanki ક્ષત્રિય રાજપૂત'),
    ('Kshatriya Thakor', 'ક્ષત્રિય ઠાકોર', 'Kshatriya / Rajput', 'thakor thakore kshatriya thakor ઠાકોર ક્ષત્રિય'),
    ('Kasbati Rajput', 'કસબાતી રાજપૂત', 'Kshatriya / Rajput', 'kasbati kasbati rajput કસબાતી રાજપૂત'),
    ('Maru Rajput', 'મારુ રાજપૂત', 'Kshatriya / Rajput', 'maru maroo rajput મારુ રાજપૂત'),
    ('Luhar Suthar', 'લુહાર સુથાર', 'Vishwakarma / Suthar', 'luhar suthar lohar suthar vishwakarma લુહાર સુથાર વિશ્વકર્મા'),
    ('Gujjar Suthar', 'ગુર્જર સુથાર', 'Vishwakarma / Suthar', 'gujjar suthar gurjar suthar vishwakarma ગુર્જર સુથાર'),
    ('Mistry Suthar', 'મિસ્ત્રી સુથાર', 'Vishwakarma / Suthar', 'mistry suthar mistri suthar મિસ્ત્રી સુથાર'),
    ('Mewada Suthar', 'મેવાડા સુથાર', 'Vishwakarma / Suthar', 'mewada mevada suthar મેવાડા સુથાર'),
    ('Vansh Suthar', 'વંશ સુથાર', 'Vishwakarma / Suthar', 'vansh suthar vanshsuthar વંશ સુથાર'),
    ('Panchal', 'પંચાલ', 'Vishwakarma / Suthar', 'panchal panchal suthar luhar પંચાલ'),
    ('Luhar', 'લુહાર', 'Vishwakarma / Suthar', 'luhar lohar black smith લુહાર'),
    ('Gujjar Luhar', 'ગુર્જર લુહાર', 'Vishwakarma / Suthar', 'gujjar luhar gurjar luhar ગુર્જર લુહાર'),
    ('Bhavnagari Luhar', 'ભાવનગરી લુહાર', 'Vishwakarma / Suthar', 'bhavnagari luhar ભાવનગરી લુહાર'),
    ('Sihori Luhar', 'શિહોરી લુહાર', 'Vishwakarma / Suthar', 'sihori luhar શિહોરી લુહાર'),
    ('Kadiwal Luhar', 'કડીવાલ લુહાર', 'Vishwakarma / Suthar', 'kadiwal luhar કડીવાલ લુહાર'),
    ('Pithva Suthar', 'પીઠવા સુથાર', 'Vishwakarma / Suthar', 'pithva pithwa suthar પીઠવા સુથાર'),
    ('Gujjar Prajapati', 'ગુર્જર પ્રજાપતિ', 'Prajapati / Kumbhar', 'gujjar prajapati gurjar prajapati ગુર્જર પ્રજાપતિ'),
    ('Varia Prajapati', 'વરિયા પ્રજાપતિ', 'Prajapati / Kumbhar', 'varia wariya prajapati વરિયા પ્રજાપતિ'),
    ('Sorathiya Prajapati', 'સોરઠીયા પ્રજાપતિ', 'Prajapati / Kumbhar', 'sorathiya sorthiya prajapati સોરઠીયા પ્રજાપતિ'),
    ('Lad Prajapati', 'લાડ પ્રજાપતિ', 'Prajapati / Kumbhar', 'lad prajapati laad prajapati લાડ પ્રજાપતિ'),
    ('Kumbhar', 'કુંભાર', 'Prajapati / Kumbhar', 'kumbhar prajapati કુંભાર'),
    ('Ajwaliya Prajapati', 'અજવાળિયા પ્રજાપતિ', 'Prajapati / Kumbhar', 'ajwaliya ajvaliya prajapati અજવાળિયા પ્રજાપતિ'),
    ('Modh Vanik', 'મોઢ વણિક', 'Vanik / Vaishnav', 'modh vanik vaniya baniya મોઢ વણિક વાણિયા'),
    ('Dasha Shrimali Vanik', 'દશા શ્રીમાળી વણિક', 'Vanik / Vaishnav', 'dasha shrimali vanik baniya દશા શ્રીમાળી વણિક'),
    ('Visa Shrimali Vanik', 'વિસા શ્રીમાળી વણિક', 'Vanik / Vaishnav', 'visa shrimali vanik baniya વિસા શ્રીમાળી વણિક'),
    ('Porwad Vanik', 'પોરવાડ વણિક', 'Vanik / Vaishnav', 'porwad porwal vanik પોરવાડ વણિક'),
    ('Khadayata Vanik', 'ખડાયતા વણિક', 'Vanik / Vaishnav', 'khadayata khadayta vanik ખડાયતા વણિક'),
    ('Kapol Vanik', 'કપોળ વણિક', 'Vanik / Vaishnav', 'kapol vanik kapol baniya કપોળ વણિક'),
    ('Harsola Vanik', 'હરસોલા વણિક', 'Vanik / Vaishnav', 'harsola vanik હરસોલા વણિક'),
    ('Lad Vanik', 'લાડ વણિક', 'Vanik / Vaishnav', 'lad vanik laad vanik લાડ વણિક'),
    ('Dasha Porwad', 'દશા પોરવાડ', 'Vanik / Vaishnav', 'dasha porwad porwal દશા પોરવાડ'),
    ('Visa Porwad', 'વિસા પોરવાડ', 'Vanik / Vaishnav', 'visa porwad porwal વિસા પોરવાડ'),
    ('Jharola Vanik', 'ઝરોળા વણિક', 'Vanik / Vaishnav', 'jharola zarola vanik ઝરોળા વણિક'),
    ('Mewada Vanik', 'મેવાડા વણિક', 'Vanik / Vaishnav', 'mewada mevada vanik મેવાડા વણિક'),
    ('Nema Vanik', 'નેમા વણિક', 'Vanik / Vaishnav', 'nema vanik નેમા વણિક'),
    ('Deshaval Vanik', 'દેશાવાળ વણિક', 'Vanik / Vaishnav', 'deshaval deshavad vanik દેશાવાળ વણિક'),
    ('Vaishnav Vanik', 'વૈષ્ણવ વણિક', 'Vanik / Vaishnav', 'vaishnav vanik vaishnav baniya વૈષ્ણવ વણિક'),
    ('Halai Lohana', 'હાલાઈ લોહાણા', 'Lohana', 'halai lohana thakkar luwana હાલાઈ લોહાણા ઠક્કર'),
    ('Ghoghari Lohana', 'ઘોઘારી લોહાણા', 'Lohana', 'ghoghari goghari lohana thakkar ઘોઘારી લોહાણા'),
    ('Kutchi Lohana', 'કચ્છી લોહાણા', 'Lohana', 'kutchi kutchhi lohana thakkar કચ્છી લોહાણા'),
    ('Vaishnav Lohana', 'વૈષ્ણવ લોહાણા', 'Lohana', 'vaishnav lohana thakkar વૈષ્ણવ લોહાણા'),
    ('Machhoya Ahir', 'મચ્છોયા આહીર', 'Ahir / Maldhari', 'machhoya ahir aahir મચ્છોયા આહીર'),
    ('Sorathiya Ahir', 'સોરઠીયા આહીર', 'Ahir / Maldhari', 'sorathiya sorthiya ahir aahir સોરઠીયા આહીર'),
    ('Boricha Ahir', 'બોરીચા આહીર', 'Ahir / Maldhari', 'boricha ahir aahir બોરીચા આહીર'),
    ('Pancholi Ahir', 'પાંચોળી આહીર', 'Ahir / Maldhari', 'pancholi ahir aahir પાંચોળી આહીર'),
    ('Paratharia Ahir', 'પરાથરિયા આહીર', 'Ahir / Maldhari', 'paratharia parathariya ahir aahir પરાથરિયા આહીર'),
    ('Rabari', 'રબારી', 'Ahir / Maldhari', 'rabari rayka desai રબારી રાયકા દેસાઈ'),
    ('Vadhiyar Rabari', 'વઢિયાર રબારી', 'Ahir / Maldhari', 'vadhiyar vadhiyari rabari વઢિયાર રબારી'),
    ('Patanwadia Rabari', 'પાટણવાડિયા રબારી', 'Ahir / Maldhari', 'patanwadia patanwadiya rabari પાટણવાડિયા રબારી'),
    ('Kutchi Rabari', 'કચ્છી રબારી', 'Ahir / Maldhari', 'kutchi kutchhi rabari કચ્છી રબારી'),
    ('Bharwad', 'ભરવાડ', 'Ahir / Maldhari', 'bharwad bharvad mota nana ભરવાડ'),
    ('Mota Bharwad', 'મોટા ભરવાડ', 'Ahir / Maldhari', 'mota bharwad મોટા ભરવાડ'),
    ('Nana Bharwad', 'નાના ભરવાડ', 'Ahir / Maldhari', 'nana bharwad નાના ભરવાડ'),
    ('Talpada Koli', 'તળપદા કોળી', 'Koli', 'talpada koli thakor તળપદા કોળી'),
    ('Chunvalia Koli', 'ચુંવાળિયા કોળી', 'Koli', 'chunvalia chunvaliya koli thakor ચુંવાળિયા કોળી'),
    ('Ghedia Koli', 'ઘેડિયા કોળી', 'Koli', 'ghedia ghediya koli ઘેડિયા કોળી'),
    ('Thakor Koli', 'ઠાકોર કોળી', 'Koli', 'thakor koli thakore ઠાકોર કોળી'),
    ('Baria Koli', 'બારિયા કોળી', 'Koli', 'baria bariya koli બારિયા કોળી'),
    ('Dharala Koli', 'ધરાળા કોળી', 'Koli', 'dharala koli ધરાળા કોળી'),
    ('Koli Patel', 'કોળી પટેલ', 'Koli', 'koli patel કોળી પટેલ'),
    ('Soni', 'સોની', 'Artisan & Trade', 'soni swarnakar goldsmith સોની'),
    ('Shrimali Soni', 'શ્રીમાળી સોની', 'Artisan & Trade', 'shrimali srimali soni શ્રીમાળી સોની'),
    ('Gujjar Soni', 'ગુર્જર સોની', 'Artisan & Trade', 'gujjar soni gurjar soni ગુર્જર સોની'),
    ('Maru Soni', 'મારુ સોની', 'Artisan & Trade', 'maru soni મારુ સોની'),
    ('Kansara', 'કંસારા', 'Artisan & Trade', 'kansara coppersmith કંસારા'),
    ('Darji', 'દરજી', 'Artisan & Trade', 'darji tailor દરજી'),
    ('Ramdev Darji', 'રામદેવ દરજી', 'Artisan & Trade', 'ramdev darji રામદેવ દરજી'),
    ('Charaniya Darji', 'ચારણીયા દરજી', 'Artisan & Trade', 'charaniya darji ચારણીયા દરજી'),
    ('Bhavsar', 'ભાવસાર', 'Artisan & Trade', 'bhavsar bhavasar ભાવસાર'),
    ('Khatri', 'ખત્રી', 'Artisan & Trade', 'khatri kshatriya ખત્રી'),
    ('Brahma Kshatriya', 'બ્રહ્મક્ષત્રિય', 'Artisan & Trade', 'brahma kshatriya brahmakshatriya બ્રહ્મક્ષત્રિય'),
    ('Ghanchi', 'ઘાંચી', 'Artisan & Trade', 'ghanchi modh ghanchi તેલી ઘાંચી'),
    ('Modh Ghanchi', 'મોઢ ઘાંચી', 'Artisan & Trade', 'modh ghanchi મોઢ ઘાંચી'),
    ('Salvi', 'સાળવી', 'Artisan & Trade', 'salvi patola weaver સાળવી'),
    ('Chhipa', 'છીપા', 'Artisan & Trade', 'chhipa printer છીપા'),
    ('Rangrez', 'રંગરેઝ', 'Artisan & Trade', 'rangrez ranger રંગરેઝ'),
    ('Tamboli', 'તંબોળી', 'Artisan & Trade', 'tamboli panwala તંબોળી'),
    ('Limbachiya', 'લિંબાચીયા', 'Valand / Limbachiya', 'limbachiya limbachia nai valand લિંબાચીયા'),
    ('Valand / Nai', 'વાણંદ / નાઈ', 'Valand / Limbachiya', 'valand vanand nai barber વાણંદ નાઈ'),
    ('Gujjar Valand', 'ગુર્જર વાણંદ', 'Valand / Limbachiya', 'gujjar valand gurjar vanand ગુર્જર વાણંદ'),
    ('Maru Charan', 'મારુ ચારણ', 'Charan / Gadhvi', 'maru charan gadhvi મારુ ચારણ ગઢવી'),
    ('Kachela Charan', 'કછેલા ચારણ', 'Charan / Gadhvi', 'kachela charan gadhvi કછેલા ચારણ ગઢવી'),
    ('Tumbel Charan', 'તુંબેલ ચારણ', 'Charan / Gadhvi', 'tumbel charan gadhvi તુંબેલ ચારણ ગઢવી'),
    ('Vankar', 'વણકર', 'Scheduled Communities', 'vankar weaver વણકર'),
    ('Rohit', 'રોહિત', 'Scheduled Communities', 'rohit chakor રોહિત'),
    ('Meghwal', 'મેઘવાલ', 'Scheduled Communities', 'meghwal maheshwari મેઘવાલ'),
    ('Maheshwari Meghwal', 'માહેશ્વરી મેઘવાલ', 'Scheduled Communities', 'maheshwari meghwal માહેશ્વરી મેઘવાલ'),
    ('Garoda', 'ગરોડા', 'Scheduled Communities', 'garoda guruda ગરોડા'),
    ('Senva', 'સેણવા', 'Scheduled Communities', 'senva senwa સેણવા'),
    ('Valmiki', 'વાલ્મીકિ', 'Scheduled Communities', 'valmiki bhangi વાલ્મીકિ'),
    ('Goswami / Bava / Sadhu', 'ગોસ્વામી / બાવા / સાધુ', 'Traditional Communities', 'goswami bava sadhu mahant puri giri bharathi ગોસ્વામી બાવા સાધુ'),
    ('Atit Goswami', 'અતીત ગોસ્વામી', 'Traditional Communities', 'atit goswami bava અતીત ગોસ્વામી'),
    ('Margi Sadhu', 'માર્ગી સાધુ', 'Traditional Communities', 'margi sadhu માર્ગી સાધુ'),
    ('Raval / Ravaldev', 'રાવળ / રાવળદેવ', 'Traditional Communities', 'raval ravaldev rawaldev રાવળ રાવળદેવ'),
    ('Bhoi', 'ભોઈ', 'Traditional Communities', 'bhoi kahar ભોઈ'),
    ('Kharwa', 'ખારવા', 'Traditional Communities', 'kharwa sagarkhedu sailor ખારવા'),
    ('Machhi', 'માછી', 'Traditional Communities', 'machhi koli machhi fisherman માછી'),
    ('Devipujak / Vaghri', 'દેવીપૂજક / વાઘરી', 'Traditional Communities', 'devipujak vaghri વાઘરી દેવીપૂજક'),
    ('Chunvalia Devipujak', 'ચુંવાળિયા દેવીપૂજક', 'Traditional Communities', 'chunvalia devipujak ચુંવાળિયા દેવીપૂજક'),
    ('Bajania', 'બાજણિયા', 'Traditional Communities', 'bajania bajaniya બાજણિયા'),
    ('Nat', 'નટ', 'Traditional Communities', 'nat acrobatics નટ'),
    ('Vanjara / Banjara', 'વણજારા / બંજારા', 'Traditional Communities', 'vanjara banjara વણજારા બંજારા'),
    ('Ode / Oad', 'ઓડ', 'Traditional Communities', 'ode oad utpanna ઓડ'),
    ('Sathwara', 'સાથવારા', 'Traditional Communities', 'sathwara sagar શાકભાજી સાથવારા'),
    ('Kadia', 'કડિયા', 'Traditional Communities', 'kadia mason કડિયા'),
    ('Gujjar Kadia', 'ગુર્જર કડિયા', 'Traditional Communities', 'gujjar kadia gurjar kadia ગુર્જર કડિયા'),
    ('Salat', 'સલાટ', 'Traditional Communities', 'salat stone artist સલાટ'),
    ('Dabgar', 'ડબગર', 'Traditional Communities', 'dabgar ડબગર'),
    ('Barot / Brahmbhatt', 'બારોટ / બ્રહ્મભટ્ટ', 'Traditional Communities', 'barot brahmbhatt bhat બારોટ બ્રહ્મભટ્ટ'),
    ('Bhat / Vahivancha Barot', 'ભાટ / વહીવંચા બારોટ', 'Traditional Communities', 'bhat vahivancha barot ભાટ વહીવંચા બારોટ'),
    ('Charan Barot', 'ચારણ બારોટ', 'Traditional Communities', 'charan barot ચારણ બારોટ')
ON CONFLICT (name) DO UPDATE SET
    guj = EXCLUDED.guj,
    caste_group = EXCLUDED.caste_group,
    keywords = EXCLUDED.keywords;
